// <auto-generated />
namespace VideoStreamingAspMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VideoModel_With_Files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VideoModel_With_Files));
        
        string IMigrationMetadata.Id
        {
            get { return "201709160041185_VideoModel_With_Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
